from __future__ import annotations

"""SIMS 입출고/거래명세서/세금계산서/월집계 공통 메타

권장 구조:
- schema_map.py  : 공용 테이블/컬럼 alias 사전
- labels_map.py  : 공용 컬럼 라벨 사전
- rddbc_io_meta.py: 복잡한 업무 규칙/연결 규칙/집계 판정

주의:
- 사용자 설명 기준으로 Rd13_Trans_Di 는 '1'=입고, '3'=출고를 기본으로 사용한다.
- 기존 문서/구현 일부에 '2'=출고 흔적이 있을 수 있어 fallback 으로 같이 허용한다.
- 첨부 SQL 샘플은 210/220 파일명이 서로 바뀌어 있었지만,
  여기서는 사용자 설명 기준으로 210=실재고월집계, 220=장부재고월집계로 고정한다.
"""

from typing import Dict, Iterable, Mapping, Tuple

TRANS_DI_IN = '1'
TRANS_DI_OUT_PRIMARY = '3'
TRANS_DI_OUT_FALLBACK = ('3', '2')

TAX_DI_IN = '1'   # 매입(입고)
TAX_DI_OUT = '3'  # 매출(출고)

REAL_STOCK_IN_PREFIXES = ('0', '1', '3', '4')
REAL_STOCK_OUT_PREFIXES = ('5', '6', '8', '9')
BOOK_STOCK_IN_PREFIXES = ('0', '1', '2', '4')
BOOK_STOCK_OUT_PREFIXES = ('5', '6', '7', '9')

IO_GU_PREFIX_NAMES = {
    '0': '입고',
    '1': '입고반품',
    '2': '장부입고',
    '3': '미결입고',
    '4': '기타입고',
    '5': '출고',
    '6': '출고반품',
    '7': '장부출고',
    '8': '미결출고',
    '9': '기타출고',
}

IO_TABLES = {
    'rddbc110': 'dbo.Rddbc110',
    'rddbc120': 'dbo.Rddbc120',
    'rddbc130': 'dbo.Rddbc130',
    'rddbc140': 'dbo.Rddbc140',
    'rddbc210': 'dbo.Rddbc210',
    'rddbc220': 'dbo.Rddbc220',
}

IO_COLS = {
    'rddbc110': {
        'yymmdd': 'Rd11_In_YyMmDd',
        'ven_cd': 'Rd11_Ven_Cd',
        'seq': 'Rd11_In_Seq',
        'stock_cd_g': 'Rd11_Stock_Cd_Gcode',
        'stock_cd': 'Rd11_Stock_Cd',
        'physic_cd': 'Rd11_Physic_Cd',
        'io_gu_g': 'Rd11_Io_Gu_Gcode',
        'io_gu': 'Rd11_Io_Gu',
        'cost_apply_cd': 'Rd11_Cost_Apply_Cd',
        'stock_apply_cd': 'Rd11_Stock_Apply_Cd',
        'unit_cost': 'Rd11_Unit_Cost',
        'qty': 'Rd11_Quantity',
        'oqty': 'Rd11_Oquantity',
        'supply_price': 'Rd11_Supply_Price',
        'tax_price': 'Rd11_Tax_Price',
        'product_no': 'Rd11_Product_No',
        'term_date': 'Rd11_Term_Date',
        'fin_unit_cost': 'Rd11_Fin_Unit_Cost',
        'fin_supply_price': 'Rd11_Fin_Supply_Price',
        'fin_tax_price': 'Rd11_Fin_Tax_Price',
        'trans_di': 'Rd11_Trans_Di',
        'trans_yymmdd': 'Rd11_Trans_YyMmDd',
        'trans_seq': 'Rd11_Trans_Seq',
        'tax_di': 'Rd11_Tax_Di',
        'tax_yymmdd': 'Rd11_Tax_YyMmDd',
        'tax_seq': 'Rd11_Tax_Seq',
        'or_yymmdd': 'Rd11_Or_YyMmDd',
        'or_seq': 'Rd11_Or_Seq',
        'orsub_seq': 'Rd11_Orsub_Seq',
        'other': 'Rd11_Other',
        'insu_price': 'Rd11_Insu_Price',
        'fixed_flag': 'Rd11_Fixed_Flag',
        'record_flag': 'Rd11_Record_Flag',
        'reform_flag': 'Rd11_Reform_Flag',
        'validation': 'Rd11_Validation',
        'validation_qty': 'Rd11_Validation_Qty',
        'link_yymmdd': 'Rd11_Link_Yymmdd',
        'link_ven_cd': 'Rd11_Link_Ven_Cd',
        'link_seq': 'Rd11_Link_Seq',
        'unify_ven_cd': 'Rd11_Unify_Ven_Cd',
        'add_date': 'Rd11_Add_Date',
        'add_cd': 'Rd11_Add_Cd',
        'mod_date': 'Rd11_Mod_Date',
        'mod_cd': 'Rd11_Mod_Cd',
        'add_time': 'Rd11_Add_Time',
        'mod_time': 'Rd11_Mod_Time',
    },
    'rddbc120': {
        'yymmdd': 'Rd12_Out_YyMmDd',
        'ven_cd': 'Rd12_Ven_Cd',
        'seq': 'Rd12_Out_Seq',
        'in_ven_cd': 'Rd12_In_Ven_Cd',
        'stock_cd_g': 'Rd12_Stock_Cd_Gcode',
        'stock_cd': 'Rd12_Stock_Cd',
        'physic_cd': 'Rd12_Physic_Cd',
        'real_ven_cd': 'Rd12_Real_Ven_Cd',
        'io_gu_g': 'Rd12_Io_Gu_Gcode',
        'io_gu': 'Rd12_Io_Gu',
        'cost_apply_cd': 'Rd12_Cost_Apply_Cd',
        'stock_apply_cd': 'Rd12_Stock_Apply_Cd',
        'unit_cost': 'Rd12_Unit_Cost',
        'qty': 'Rd12_Quantity',
        'oqty': 'Rd12_Oquantity',
        'supply_price': 'Rd12_Supply_Price',
        'tax_price': 'Rd12_Tax_Price',
        'product_no': 'Rd12_Product_No',
        'term_date': 'Rd12_Term_Date',
        'sales_man': 'Rd12_Sales_Man',
        'fin_unit_cost': 'Rd12_Fin_Unit_Cost',
        'fin_supply_price': 'Rd12_Fin_Supply_Price',
        'fin_tax_price': 'Rd12_Fin_Tax_Price',
        'trans_di': 'Rd12_Trans_Di',
        'trans_yymmdd': 'Rd12_Trans_YyMmDd',
        'trans_seq': 'Rd12_Trans_Seq',
        'tax_di': 'Rd12_Tax_Di',
        'tax_yymmdd': 'Rd12_Tax_YyMmDd',
        'tax_seq': 'Rd12_Tax_Seq',
        'in_unit_cost': 'Rd12_In_Unit_Cost',
        'fin_in_unit_cost': 'Rd12_Fin_In_Unit_Cost',
        're_yymmdd': 'Rd12_Re_YyMmDd',
        're_seq': 'Rd12_Re_Seq',
        'resub_seq': 'Rd12_Resub_Seq',
        'dc_amt': 'Rd12_Dc_Amt',
        'other': 'Rd12_Other',
        'insu_price': 'Rd12_Insu_Price',
        'fixed_flag': 'Rd12_Fixed_Flag',
        'record_flag': 'Rd12_Record_Flag',
        'reform_flag': 'Rd12_Reform_Flag',
        'validation': 'Rd12_Validation',
        'sales_unit': 'Rd12_Sales_Unit',
        'sales_supply_price': 'Rd12_Sales_Supply_Price',
        'sales_tax_price': 'Rd12_Sales_Tax_Price',
        'position_num': 'Rd12_Position_Num',
        'real_sales_man': 'Rd12_Real_Sales_Man',
        'validation_qty': 'Rd12_Validation_Qty',
        'add_date': 'Rd12_Add_Date',
        'add_cd': 'Rd12_Add_Cd',
        'mod_date': 'Rd12_Mod_Date',
        'mod_cd': 'Rd12_Mod_Cd',
        'add_time': 'Rd12_Add_Time',
        'mod_time': 'Rd12_Mod_Time',
    },
    'rddbc130': {
        'trans_di': 'Rd13_Trans_Di',
        'trans_yymmdd': 'Rd13_Trans_YyMmDd',
        'ven_cd': 'Rd13_Ven_Cd',
        'trans_seq': 'Rd13_Trans_Seq',
        'delivery_di_g': 'Rd13_Delivery_Di_Gcode',
        'delivery_di': 'Rd13_Delivery_Di',
        'supply_price': 'Rd13_Supply_Price',
        'tax_price': 'Rd13_Tax_Price',
        'tot_amt': 'Rd13_Tot_Amt',
        'cash_amt': 'Rd13_Cash_Amt',
        'note_amt': 'Rd13_Note_Amt',
        'bill_amt': 'Rd13_Bill_Amt',
        'credit_amt': 'Rd13_Credit_Amt',
        'tax_ven_cd': 'Rd13_TAX_VEN_CD',
        'delivery_man': 'Rd13_Delivery_Man',
        'sales_man': 'Rd13_Sales_Man',
        'remark': 'Rd13_Remark',
        'print_seq': 'Rd13_Print_Seq',
        'add_date': 'Rd13_Add_Date',
        'add_cd': 'Rd13_Add_Cd',
        'mod_date': 'Rd13_Mod_Date',
        'mod_cd': 'Rd13_Mod_Cd',
        'add_time': 'Rd13_Add_Time',
        'mod_time': 'Rd13_Mod_Time',
    },
    'rddbc140': {
        'tax_di': 'Rd14_Tax_Di',
        'tax_yymmdd': 'Rd14_Tax_YyMmDd',
        'ven_cd': 'Rd14_Ven_Cd',
        'tax_seq': 'Rd14_Tax_Seq',
        'tax_di_g': 'Rd14_Tax_Di_Gcode',
        'ven_num': 'Rd14_Ven_Num',
        'supply_price': 'Rd14_Supply_Price',
        'tax_price': 'Rd14_Tax_Price',
        'space_cnt': 'Rd14_Space_Cnt',
        'tot_amt': 'Rd14_Tot_Amt',
        'cash_amt': 'Rd14_Cash_Amt',
        'note_amt': 'Rd14_Note_Amt',
        'bill_amt': 'Rd14_Bill_Amt',
        'credit_amt': 'Rd14_Credit_Amt',
        'tax_gu_g': 'Rd14_Tax_Gu_Gcode',
        'tax_gu': 'Rd14_Tax_Gu',
        'process_gu': 'Rd14_Process_Gu',
        'slip_gubun': 'Rd14_Slip_Gubun',
        'slip_yymmdd': 'Rd14_Slip_YyMmDd',
        'slip_no': 'Rd14_Slip_No',
        'slip_seq': 'Rd14_Slip_Seq',
        'remark': 'Rd14_Remark',
        'tax_bill_g': 'Rd14_Tax_Bill_Gcode',
        'tax_bill': 'Rd14_Tax_Bill',
        'mod_gu': 'Rd14_Mod_Gu',
        'report_date': 'Rd14_Report_Date',
        'e_tax_gu': 'Rd14_E_Tax_Gu',
        'add_date': 'Rd14_Add_Date',
        'add_cd': 'Rd14_Add_Cd',
        'mod_date': 'Rd14_Mod_Date',
        'mod_cd': 'Rd14_Mod_Cd',
        'print_seq': 'Rd14_Print_Seq',
    },
    'rddbc210': {
        'physic_cd': 'Rd21_Physic_Cd',
        'stock_cd': 'Rd21_Stock_Cd',
        'stock_yymm': 'Rd21_Stock_YyMm',
        'ven_cd': 'Rd21_Ven_Cd',
        'stock_apply_cd': 'Rd21_Stock_Apply_Cd',
        'io_gu': 'Rd21_Io_Gu',
        'stock_cd_g': 'Rd21_Stock_Cd_Gcode',
        'io_gu_g': 'Rd21_Io_Gu_Gcode',
        'in_qty': 'Rd21_In_Quantity',
        'in_oqty': 'Rd21_In_Oquantity',
        'in_supply_price': 'Rd21_In_Supply_Price',
        'in_tax_price': 'Rd21_In_Tax_Price',
        'out_qty': 'Rd21_Out_Quantity',
        'out_oqty': 'Rd21_Out_Oquantity',
        'out_supply_price': 'Rd21_Out_Supply_Price',
        'out_tax_price': 'Rd21_Out_Tax_Price',
    },
    'rddbc220': {
        'physic_cd': 'Rd22_Physic_Cd',
        'stock_cd': 'Rd22_Stock_Cd',
        'stock_yymm': 'Rd22_Stock_YyMm',
        'ven_cd': 'Rd22_Ven_Cd',
        'stock_apply_cd': 'Rd22_Stock_Apply_Cd',
        'io_gu': 'Rd22_Io_Gu',
        'stock_cd_g': 'Rd22_Stock_Cd_Gcode',
        'io_gu_g': 'Rd22_Io_Gu_Gcode',
        'in_qty': 'Rd22_In_Quantity',
        'in_oqty': 'Rd22_In_Oquantity',
        'in_supply_price': 'Rd22_In_Supply_Price',
        'in_tax_price': 'Rd22_In_Tax_Price',
        'out_qty': 'Rd22_Out_Quantity',
        'out_oqty': 'Rd22_Out_Oquantity',
        'out_supply_price': 'Rd22_Out_Supply_Price',
        'out_tax_price': 'Rd22_Out_Tax_Price',
    },
}

IO_LABELS = {
    "rddbc110": {
        "Rd11_In_YyMmDd": "입고일자",
        "Rd11_Ven_Cd": "거래처코드",
        "Rd11_In_Seq": "입고순번",
        "Rd11_Stock_Cd_Gcode": "재고위치대분류코드",
        "Rd11_Stock_Cd": "재고위치코드",
        "Rd11_Physic_Cd": "제품코드",
        "Rd11_Io_Gu_Gcode": "입출고구분대분류코드",
        "Rd11_Io_Gu": "입출고구분코드",
        "Rd11_Cost_Apply_Cd": "단가적용처코드",
        "Rd11_Stock_Apply_Cd": "재고적용처코드",
        "Rd11_Unit_Cost": "단가",
        "Rd11_Quantity": "수량",
        "Rd11_Oquantity": "할증수량",
        "Rd11_Supply_Price": "공급가액",
        "Rd11_Tax_Price": "세액",
        "Rd11_Product_No": "제조번호",
        "Rd11_Term_Date": "유효기간",
        "Rd11_Fin_Unit_Cost": "확정단가",
        "Rd11_Fin_Supply_Price": "확정공급가액",
        "Rd11_Fin_Tax_Price": "확정세액",
        "Rd11_Trans_Di": "거래명세서구분",
        "Rd11_Trans_YyMmDd": "거래명세서일자",
        "Rd11_Trans_Seq": "거래명세서순번",
        "Rd11_Tax_Di": "세금계산서구분",
        "Rd11_Tax_YyMmDd": "세금계산서일자",
        "Rd11_Tax_Seq": "세금계산서순번",
        "Rd11_Or_YyMmDd": "발주일자",
        "Rd11_Or_Seq": "발주순번",
        "Rd11_Orsub_Seq": "발주상세순번",
        "Rd11_Other": "비고",
        "Rd11_Insu_Price": "보험단가",
        "Rd11_Fixed_Flag": "마감FLAG",
        "Rd11_Record_Flag": "전표발행FLAG",
        "Rd11_Reform_Flag": "세무관리FLAG",
        "Rd11_Validation": "검수FLAG",
        "Rd11_Add_Date": "등록일자",
        "Rd11_Add_Cd": "등록자코드",
        "Rd11_Mod_Date": "수정일자",
        "Rd11_Mod_Cd": "수정자코드",
        "Rd11_Dope_Flag": "특수약품FLAG",
        "Rd11_Unify_Ven_Cd": "통합거래처코드",
        "Rd11_Validation_Qty": "검수수량",
        "Rd11_Add_Time": "등록시간",
        "Rd11_Mod_Time": "수정시간",
        "거래처명": "거래처명",
        "재고위치명": "재고위치명",
        "제품명": "제품명",
        "입출고구분명": "입출고구분명",
        "단가적용처명": "단가적용처명",
        "재고적용처명": "재고적용처명",
        "등록자명": "등록자명",
        "수정자명": "수정자명",
        "Io_Gu_Prefix": "입출고구분앞자리",
        "거래명세서상세합_공급가액": "거래명세서상세합_공급가액",
        "거래명세서상세합_세액": "거래명세서상세합_세액",
        "거래명세서헤더_공급가액": "거래명세서헤더_공급가액",
        "거래명세서헤더_세액": "거래명세서헤더_세액",
        "거래명세서금액일치": "거래명세서금액일치",
        "세금계산서상세합_공급가액": "세금계산서상세합_공급가액",
        "세금계산서상세합_세액": "세금계산서상세합_세액",
        "세금계산서헤더_공급가액": "세금계산서헤더_공급가액",
        "세금계산서헤더_세액": "세금계산서헤더_세액",
        "세금계산서금액일치": "세금계산서금액일치",
    },

    "rddbc120": {
        "Rd12_Out_YyMmDd": "출고일자",
        "Rd12_Ven_Cd": "거래처코드",
        "Rd12_Out_Seq": "출고순번",
        "Rd12_In_Ven_Cd": "매입처코드",
        "Rd12_Stock_Cd_Gcode": "재고위치대분류코드",
        "Rd12_Stock_Cd": "재고위치코드",
        "Rd12_Physic_Cd": "제품코드",
        "Rd12_Real_Ven_Cd": "실납처코드",
        "Rd12_Io_Gu_Gcode": "입출고구분대분류코드",
        "Rd12_Io_Gu": "입출고구분코드",
        "Rd12_Cost_Apply_Cd": "단가적용처코드",
        "Rd12_Stock_Apply_Cd": "재고적용처코드",
        "Rd12_Unit_Cost": "단가",
        "Rd12_Quantity": "수량",
        "Rd12_Oquantity": "할증수량",
        "Rd12_Supply_Price": "공급가액",
        "Rd12_Tax_Price": "세액",
        "Rd12_Product_No": "제조번호",
        "Rd12_Term_Date": "유효기간",
        "Rd12_Fin_Unit_Cost": "확정단가",
        "Rd12_Fin_Supply_Price": "확정공급가액",
        "Rd12_Fin_Tax_Price": "확정세액",
        "Rd12_Trans_Di": "거래명세서구분",
        "Rd12_Trans_YyMmDd": "거래명세서일자",
        "Rd12_Trans_Seq": "거래명세서순번",
        "Rd12_Tax_Di": "세금계산서구분",
        "Rd12_Tax_YyMmDd": "세금계산서일자",
        "Rd12_Tax_Seq": "세금계산서순번",
        "Rd12_In_Unit_Cost": "실입고단가",
        "Rd12_Fin_In_Unit_Cost": "장부입고단가",
        "Rd12_Re_YyMmDd": "수주일자",
        "Rd12_Re_Seq": "수주순번",
        "Rd12_Resub_Seq": "수주상세순번",
        "Rd12_Dc_Amt": "출고할인금액",
        "Rd12_Other": "비고",
        "Rd12_Insu_Price": "보험단가",
        "Rd12_Fixed_Flag": "마감FLAG",
        "Rd12_Record_Flag": "전표발행FLAG",
        "Rd12_Reform_Flag": "세무관리FLAG",
        "Rd12_Validation": "검수FLAG",
        "Rd12_Add_Date": "등록일자",
        "Rd12_Add_Cd": "등록자코드",
        "Rd12_Mod_Date": "수정일자",
        "Rd12_Mod_Cd": "수정자코드",
        "Rd12_Sales_Unit": "영업사원단가",
        "Rd12_Sales_Supply_Price": "영업사원공급가액",
        "Rd12_Sales_Tax_Price": "영업사원세액",
        "Rd12_Dope_Flag": "특수약품FLAG",
        "Rd12_Position_Num": "확정순번",
        "Rd12_Real_Sales_Man": "확정영업사원",
        "Rd12_Validation_Qty": "검수수량",
        "Rd12_Add_Time": "등록시간",
        "Rd12_Mod_Time": "수정시간",
        "Rd12_Prod_Date": "제조년월일",
        "거래처명": "거래처명",
        "매입처명": "매입처명",
        "재고위치명": "재고위치명",
        "재고위치": "재고위치",
        "제품명": "제품명",
        "실납처명": "실납처명",
        "입출고구분명": "입출고구분명",
        "입출고구분": "입출고구분",
        "단가적용처명": "단가적용처명",
        "재고적용처명": "재고적용처명",
        "등록자명": "등록자명",
        "수정자명": "수정자명",
        "Io_Gu_Prefix": "입출고구분앞자리",
        "거래명세서상세합_공급가액": "거래명세서상세합_공급가액",
        "거래명세서상세합_세액": "거래명세서상세합_세액",
        "거래명세서헤더_공급가액": "거래명세서헤더_공급가액",
        "거래명세서헤더_세액": "거래명세서헤더_세액",
        "거래명세서금액일치": "거래명세서금액일치",
        "세금계산서상세합_공급가액": "세금계산서상세합_공급가액",
        "세금계산서상세합_세액": "세금계산서상세합_세액",
        "세금계산서헤더_공급가액": "세금계산서헤더_공급가액",
        "세금계산서헤더_세액": "세금계산서헤더_세액",
        "세금계산서금액일치": "세금계산서금액일치",
    },

    "rddbc130": {
        "Rd13_Trans_Di": "거래명세서구분",
        "Rd13_Trans_YyMmDd": "거래명세서일자",
        "Rd13_Ven_Cd": "거래처코드",
        "Rd13_Trans_Seq": "거래명세서순번",
        "Rd13_Supply_Price": "공급가액",
        "Rd13_Tax_Price": "세액",
        "Rd13_Tot_Amt": "합계금액",
        "Rd13_Dc_Amt": "할인금액",
        "Rd13_Slip_Gubun": "전표발행구분",
        "Rd13_Slip_YyMmDd": "전표발행일자",
        "Rd13_Slip_No": "전표번호",
        "Rd13_Slip_Seq": "전표순번",
        "Rd13_Other": "비고",
        "Rd13_Confirm_Check": "인수증확인",
        "Rd13_Add_Date": "등록일자",
        "Rd13_Add_Cd": "등록자코드",
        "Rd13_Mod_Date": "수정일자",
        "Rd13_Mod_Cd": "수정자코드",
        "Rd13_Delivery_Di_Gcode": "배송구분대분류코드",
        "Rd13_Delivery_Di": "배송구분코드",
        "Rd13_Print_Seq": "명세서출력횟수",
        "Rd13_Confirm_Check2": "인수증체크2",
        "Rd13_Confirm_Check3": "인수증체크3",
        "Rd13_Delivery_Pill": "배송매약수량",
        "Rd13_Delivery_Aque": "배송물약수량",
        "Rd13_Delivery_Refriger": "배송냉장수량",
        "Rd13_Delivery_Change": "배송교체수량",
        "Rd13_Delivery_PrinterSeq": "배송순번",
        "Rd13_Delivery_Confirm": "배송인수증수량",
        "Rd13_Sales_Man_Seq": "영업사원수량",
        "Rd13_Picking_PrinterSeq": "피킹출력순번",
        "Rd13_Delivery_Degree": "배송차수",
        "Rd13_Add_Time": "등록일시",
        "Rd13_Mod_Time": "수정일시",
        "거래처명": "거래처명",
        "배송구분": "배송구분",
        "등록자명": "등록자명",
        "수정자명": "수정자명",
    },

    "rddbc140": {
        "Rd14_Tax_Di": "세금계산서구분",
        "Rd14_Tax_YyMmDd": "세금계산서일자",
        "Rd14_Ven_Cd": "거래처코드",
        "Rd14_Tax_Seq": "세금계산서순번",
        "Rd14_Tax_Di_Gcode": "세금계산서구분대분류코드",
        "Rd14_Ven_Num": "등록번호",
        "Rd14_Supply_Price": "공급가액",
        "Rd14_Tax_Price": "세액",
        "Rd14_Space_Cnt": "공란수",
        "Rd14_Ym1": "월일1",
        "Rd14_Item1": "제품1",
        "Rd14_Standard1": "규격1",
        "Rd14_Qty1": "수량1",
        "Rd14_Unit_Cost1": "단가1",
        "Rd14_Supply_Price1": "공급가액1",
        "Rd14_Tax_Price1": "세액1",
        "Rd14_Ym2": "월일2",
        "Rd14_Item2": "제품2",
        "Rd14_Standard2": "규격2",
        "Rd14_Qty2": "수량2",
        "Rd14_Unit_Cost2": "단가2",
        "Rd14_Supply_Price2": "공급가액2",
        "Rd14_Tax_Price2": "세액2",
        "Rd14_Ym3": "월일3",
        "Rd14_Item3": "제품3",
        "Rd14_Standard3": "규격3",
        "Rd14_Qty3": "수량3",
        "Rd14_Unit_Cost3": "단가3",
        "Rd14_Supply_Price3": "공급가액3",
        "Rd14_Tax_Price3": "세액3",
        "Rd14_Ym4": "월일4",
        "Rd14_Item4": "제품4",
        "Rd14_Standard4": "규격4",
        "Rd14_Qty4": "수량4",
        "Rd14_Unit_Cost4": "단가4",
        "Rd14_Supply_Price4": "공급가액4",
        "Rd14_Tax_Price4": "세액4",
        "Rd14_Tot_Amt": "합계금액",
        "Rd14_Cash_Amt": "현금",
        "Rd14_Note_Amt": "수표",
        "Rd14_Bill_Amt": "어음",
        "Rd14_Credit_Amt": "외상미수금",
        "Rd14_Tax_Gu_Gcode": "세금계산서종류대분류코드",
        "Rd14_Tax_Gu": "세금계산서종류코드",
        "Rd14_Process_Gu": "신고구분",
        "Rd14_Slip_Gubun": "전표발행구분",
        "Rd14_Slip_YyMmDd": "회계일자",
        "Rd14_Slip_Yy": "회계년도",
        "Rd14_Slip_Mm": "회계월",
        "Rd14_Slip_Dd": "회계일",
        "Rd14_Slip_No": "회계전표번호",
        "Rd14_Slip_Seq": "회계전표순번",
        "Rd14_Add_Date": "등록일자",
        "Rd14_Add_Cd": "등록자코드",
        "Rd14_Mod_Date": "수정일자",
        "Rd14_Mod_Cd": "수정자코드",
        "Rd14_Print_Seq": "프린트출력순서",
        "Rd14_Tax_Pair": "사업자등록번호묶음발행여부",
        "Rd14_Move_Seq": "IF번호",
        "Rd14_Move_Date": "IF일자",
        "Rd14_Credit_No": "신용카드번호",
        "Rd14_E_Tax_Gu": "전자세금계산서전송여부",
        "Rd14_Remark": "비고",
        "Rd14_Tax_Bill_Gcode": "영수청구구분대분류코드",
        "Rd14_Tax_Bill": "영수청구구분",
        "Rd14_Mod_Gu": "수정가능여부",
        "Rd14_Print_Other": "출력메모",
        "Rd14_Report_Date": "전자세금계산서송부일자",
        "Rd14_Ven_Num_Sub": "종사업자번호",
        "거래처명": "거래처명",
        "세금계산서구분명": "세금계산서구분명",
        "등록자명": "등록자명",
        "수정자명": "수정자명",
    },

    "rddbc210": {
        "Rd21_Physic_Cd": "제품코드",
        "Rd21_Stock_Cd": "재고위치코드",
        "Rd21_Stock_YyMm": "재고년월",
        "Rd21_Ven_Cd": "거래처코드",
        "Rd21_Stock_Apply_Cd": "재고적용처코드",
        "Rd21_Io_Gu": "입출고구분코드",
        "Rd21_Stock_Cd_Gcode": "재고위치대분류코드",
        "Rd21_Io_Gu_Gcode": "입출고구분대분류코드",
        "Rd21_In_Quantity": "입고수량",
        "Rd21_In_Oquantity": "입고할증수량",
        "Rd21_In_Supply_Price": "입고공급가액",
        "Rd21_In_Tax_Price": "입고세액",
        "Rd21_Out_Quantity": "출고수량",
        "Rd21_Out_Oquantity": "출고할증수량",
        "Rd21_Out_Supply_Price": "출고공급가액",
        "Rd21_Out_Tax_Price": "출고세액",
        "제품명": "제품명",
        "재고위치": "재고위치",
        "거래처명": "거래처명",
        "재고적용처명": "재고적용처명",
        "입출고구분": "입출고구분",
    },

    "rddbc220": {
        "Rd22_Physic_Cd": "제품코드",
        "Rd22_Stock_Cd": "재고위치코드",
        "Rd22_Stock_YyMm": "재고년월",
        "Rd22_Ven_Cd": "거래처코드",
        "Rd22_Stock_Apply_Cd": "재고적용처코드",
        "Rd22_Io_Gu": "입출고구분코드",
        "Rd22_Stock_Cd_Gcode": "재고위치대분류코드",
        "Rd22_Io_Gu_Gcode": "입출고구분대분류코드",
        "Rd22_In_Quantity": "입고수량",
        "Rd22_In_Oquantity": "입고할증수량",
        "Rd22_In_Supply_Price": "입고공급가액",
        "Rd22_In_Tax_Price": "입고세액",
        "Rd22_Out_Quantity": "출고수량",
        "Rd22_Out_Oquantity": "출고할증수량",
        "Rd22_Out_Supply_Price": "출고공급가액",
        "Rd22_Out_Tax_Price": "출고세액",
        "제품명": "제품명",
        "재고위치": "재고위치",
        "거래처명": "거래처명",
        "재고적용처명": "재고적용처명",
        "입출고구분": "입출고구분",
    },
}

IO_PK = {
    'rddbc110': ('Rd11_In_YyMmDd', 'Rd11_Ven_Cd', 'Rd11_In_Seq'),
    'rddbc120': ('Rd12_Out_YyMmDd', 'Rd12_Ven_Cd', 'Rd12_Out_Seq'),
    'rddbc130': ('Rd13_Trans_Di', 'Rd13_Trans_YyMmDd', 'Rd13_Ven_Cd', 'Rd13_Trans_Seq'),
    'rddbc140': ('Rd14_Tax_Di', 'Rd14_Tax_YyMmDd', 'Rd14_Ven_Cd', 'Rd14_Tax_Seq'),
    'rddbc210': ('Rd21_Physic_Cd', 'Rd21_Stock_Cd', 'Rd21_Stock_YyMm', 'Rd21_Ven_Cd', 'Rd21_Stock_Apply_Cd', 'Rd21_Io_Gu'),
    'rddbc220': ('Rd22_Physic_Cd', 'Rd22_Stock_Cd', 'Rd22_Stock_YyMm', 'Rd22_Ven_Cd', 'Rd22_Stock_Apply_Cd', 'Rd22_Io_Gu'),
}

IO_RELATIONS = {
    'rddbc110': {
        'to_rddbc130': {
            'left': ('Rd11_Trans_YyMmDd', 'Rd11_Ven_Cd', 'Rd11_Trans_Seq'),
            'right': ('Rd13_Trans_YyMmDd', 'Rd13_Ven_Cd', 'Rd13_Trans_Seq'),
            'right_fixed': {'Rd13_Trans_Di': TRANS_DI_IN},
        },
        'to_rddbc140': {
            'left': ('Rd11_Tax_Di', 'Rd11_Tax_YyMmDd', 'Rd11_Ven_Cd', 'Rd11_Tax_Seq'),
            'right': ('Rd14_Tax_Di', 'Rd14_Tax_YyMmDd', 'Rd14_Ven_Cd', 'Rd14_Tax_Seq'),
            'left_required': {'Rd11_Tax_Di': TAX_DI_IN},
            'right_fixed': {'Rd14_Tax_Di': TAX_DI_IN},
        },
    },
    'rddbc120': {
        'to_rddbc130': {
            'left': ('Rd12_Trans_YyMmDd', 'Rd12_Ven_Cd', 'Rd12_Trans_Seq'),
            'right': ('Rd13_Trans_YyMmDd', 'Rd13_Ven_Cd', 'Rd13_Trans_Seq'),
            'right_fixed_candidates': ({'Rd13_Trans_Di': '3'}, {'Rd13_Trans_Di': '2'}),
        },
        'to_rddbc140': {
            'left': ('Rd12_Tax_Di', 'Rd12_Tax_YyMmDd', 'Rd12_Ven_Cd', 'Rd12_Tax_Seq'),
            'right': ('Rd14_Tax_Di', 'Rd14_Tax_YyMmDd', 'Rd14_Ven_Cd', 'Rd14_Tax_Seq'),
            'left_required': {'Rd12_Tax_Di': TAX_DI_OUT},
            'right_fixed': {'Rd14_Tax_Di': TAX_DI_OUT},
        },
    },
}


def normalize_io_gu(value: object) -> str:
    if value is None:
        return ''
    text = str(value).strip()
    if not text:
        return ''
    return text.zfill(3)



def io_prefix(value: object) -> str:
    code = normalize_io_gu(value)
    return code[:1] if code else ''



def io_bucket_name(value: object) -> str:
    return IO_GU_PREFIX_NAMES.get(io_prefix(value), '미정')



def is_inbound_io(value: object) -> bool:
    return io_prefix(value) in {'0', '1', '2', '3', '4'}



def is_outbound_io(value: object) -> bool:
    return io_prefix(value) in {'5', '6', '7', '8', '9'}



def is_real_stock_target(table_name: str, io_gu: object) -> bool:
    p = io_prefix(io_gu)
    if table_name == 'rddbc110':
        return p in REAL_STOCK_IN_PREFIXES
    if table_name == 'rddbc120':
        return p in REAL_STOCK_OUT_PREFIXES
    return False



def is_books_stock_target(table_name: str, io_gu: object) -> bool:
    p = io_prefix(io_gu)
    if table_name == 'rddbc110':
        return p in BOOK_STOCK_IN_PREFIXES
    if table_name == 'rddbc120':
        return p in BOOK_STOCK_OUT_PREFIXES
    return False



def trans_di_candidates_for_output() -> Tuple[str, ...]:
    return TRANS_DI_OUT_FALLBACK



def pk_columns(table_name: str) -> Tuple[str, ...]:
    return IO_PK[table_name]
