# app/db/labels_map.py
from app.sims.meta.rddbc_io_meta import IO_LABELS

LABELS = {
    'rddbc010': {
        'Rd01_Gcode': '그룹코드',
        'Rd01_Tcode': '항목코드',
        'Rd01_Hnm':   '항목명(한글)',
        'Rd01_Enm':   '항목명(영문)',
        'Rd01_Snm':   '항목명(약칭)',
        'Rd01_Other1':'기타1',
        'Rd01_Other2':'기타2',
        'Rd01_Other3':'기타3',
        'Rd01_Col_Num':'열번호',
        'Rd01_Mod_Flag':'수정플래그',
        'Rd01_Del_Flag':'삭제여부',
        'Rd01_Add_Date':'등록일자',
        'Rd01_Add_Cd':'등록자',
        'Rd01_Mod_Date':'수정일자',
        'Rd01_Mod_Cd':'수정자',
        'Rd01_Debit_Acc_Cd1':'차변계정1',
        'Rd01_Debit_Acc_Cd2':'차변계정2',
        'Rd01_Credit_Acc_Cd1':'대변계정1',
        'Rd01_Credit_Acc_Cd2':'대변계정2',
        'kind_name':  '코드종류',
        'add_user_nm': '등록자명',
        'mod_user_nm': '수정자명',
    },
    'rddbc060': {
        'Rd06_User_Cd': '사용자코드',
        'Rd06_User_ID': '사용자ID',
        'Rd06_Password':'비밀번호',
        'Rd06_Sabun': '사번',
        'Rd06_User_Nm': '사용자명',
        'Rd06_Sex': '성별',
        'Rd06_BirthDay': '생일',
        'Rd06_Jumin': '주민등록번호',
        'Rd06_Department_Gcode': '부서그룹코드',
        'Rd06_Department': '부서코드',
        'Rd06_Duty_Gcode': '직무그룹코드',
        'Rd06_Duty': '직무코드',
        'Rd06_District_Gcode': '지역그룹코드',
        'Rd06_District': '지역코드',
        'Rd06_Email': '이메일',
        'Rd06_Cellular_Phone': '핸드폰',
        'Rd06_Phone': '집전화',
        'Rd06_Office_Phone': '회사전화',
        'Rd06_Hire_Date': '입사일자',
        'Rd06_Retire_Date': '퇴사일자',
        'Rd06_Remark': '비고',
        'Rd06_Add_Date': '등록일자',
        'Rd06_Add_Cd': '등록자',
        'Rd06_Mod_Date': '수정일자',
        'Rd06_Mod_Cd': '수정자',
        'Rd06_Mod_Flag': '수정플래그',
        'Rd06_Del_Flag': '삭제여부',
    },

    'rddbc021': {
        'Rd021_RoadCd': '도로명코드',
        'Rd021_DongSeq': '도로명코드상세번호',
        'Rd021_RoadNm': '도로명',
        'Rd021_RoadEnm': '도로명(영문)',
        'Rd021_Sido': '시도명',
        'Rd021_Gugun': '시구군명',
        'Rd021_DongGu': '동여부',
        'Rd021_DongCd': '지번본번',
        'Rd021_DongNm': '법정읍면동명',
    },

    # 🔹 Rddbc030: 거래처마스터
    'rddbc030': {
        'Rd03_Ven_Cd':        '거래처코드',
        'Rd03_Ven_Nm':        '거래처명',
        'Rd03_Owner_Nm':      '대표자명',
        'Rd03_Ven_Num':       '사업자등록번호',
        'Rd03_CorpReg_Num':   '법인등록번호',
        'Rd03_Zip_Code':      '우편번호',
        'Rd03_Zip_Seq':       '우편번호순번',
        'Rd03_Address':       '주소',
        'Rd03_Address2':      '주소2',
        'Rd03_Phone':         '전화번호',
        'Rd03_Fax':           '팩스번호',
        'Rd03_HP':            '핸드폰',
        'Rd03_EMail':         '이메일',
        'Rd03_Ven_Group_Gcode': '거래처그룹코드(그룹)',
        'Rd03_Ven_Group':       '거래처그룹코드',
        'Rd03_Ven_Kind_Gcode':  '거래처종류코드(그룹)',
        'Rd03_Ven_Kind':        '거래처종류코드',
        'Rd03_Ven_Rank_Gcode':  '거래처등급코드(그룹)',
        'Rd03_Ven_Rank':        '거래처등급코드',
        'Rd03_TAX_VEN_CD':    '세무용거래처코드',
        'Rd03_Unify_Ven_Cd':  '통합거래처코드',
        'Rd03_Cost_Apply_Cd': '원가적용코드',
        'Rd03_Stock_Apply_Cd':'재고적용코드',
        'Rd03_Delivery_Di_Gcode': '배송구분코드(그룹)',
        'Rd03_Delivery_Di':       '배송구분코드',
        'Rd03_Remark':        '비고',
        'Rd03_Add_Date':      '등록일자',
        'Rd03_Add_Cd':        '등록자',
        'Rd03_Mod_Date':      '수정일자',
        'Rd03_Mod_Cd':        '수정자',
        'Rd03_Del_Flag':      '삭제여부',
        'Rd03_Ven_Sm':    '거래처약어명',
        'Rd03_Sales_Man': '영업사원코드',
        'sales_man_nm':   '영업사원명',
        'Ven_Group_Name':     '거래처그룹명',
        'Ven_Kind_Name':      '거래처종류명',
        'Ven_Rank_Name':      '거래처등급명',
        'add_user_nm':        '등록자명',
        'mod_user_nm':        '수정자명',
    },
    'rddbc040': {
        'Rd04_Physic_Cd': '제품코드',
        'Rd04_Insu_Cd': '보험코드',
        'Rd04_Physic_Nm': '제품명',
        'Rd04_Physic_PRT': '출력명',
        'Rd04_Physic_Sm': '약어명',
        'Rd04_Ven_Cd': '제약사코드',
        'Rd04_Physic_Group_Gcode': '제품그룹 대분류',
        'Rd04_Physic_Group': '제품그룹 코드',
        'Rd04_Physic_Di_Gcode': '구분 대분류',
        'Rd04_Physic_Di': '구분 코드',
        'Rd04_Physic_Flag_Gcode': '제품플래그 대분류',
        'Rd04_Physic_Flag': '제품플래그 코드',
        'Rd04_Cons_Gcode': '함량 대분류',
        'Rd04_Cons': '함량 코드',
        'Rd04_Physic_Gu_Gcode': '제품분류 대분류',
        'Rd04_Physic_Gu': '제품분류 코드',
        'Rd04_Standard': '규격',
        'Rd04_Unit': '단위',
        'Rd04_Insu_Date': '보험적용일',
        'Rd04_Insu_Price': '보험약가',
        'Rd04_Bar_Code1': '바코드1',
        'Rd04_Bar_Code2': '바코드2',
        'Rd04_Bar_Code3': '바코드3',
        'Rd04_Bar_Code4': '바코드4',
        'Rd04_Bar_Code5': '바코드5',
        'Rd04_Use_Gu': '사용구분',
        'Rd04_Del_Flag': '삭제/사용여부',
        'Rd04_Add_Date': '등록일자',
        'Rd04_Add_Cd': '등록자',
        'Rd04_Mod_Date': '수정일자',
        'Rd04_Mod_Cd': '수정자',
        'ven_nm': '제약사명',
        'group_name': '제품그룹명',
        'di_name': '구분명',
        'flag_name': '제품플래그명',
        'cons_name': '함량명',
        'physic_gu_name': '제품분류명',
        'add_user_nm': '등록자명',
        'mod_user_nm': '수정자명',
    },
    **IO_LABELS,
}
